### PR TITLE
Fixed some more translations

### PR DESCRIPTION
**Pull request by delphiactual**
~~All translations are complete.~~

- [x] Buttons - https://github.com/angular-translate/angular-translate/issues/1006#issuecomment-93023564
   - [x] `Show/Hide {{class}} gear` 
   - [x] `Advanced Options`
   - [x] `Need Help?`
- [x] Do not equip no-stat items with `Lock Equipped` button
- [ ] Translate mouse hover for stats (Only the stat name needs translate, tier progess already is)
- [x] Add word wrap for excessively long translation for armor names

### CODE REVIEW

**Comment by delphiactual** [comment]
Some of the german strings for armor locations are rather long, these are the official translations direct from Bungie. Is there any way you can adjust this to look better. All the other language layouts look great!
screenshot 2016-10-31 23 47 22

**Comment by delphiactual** [comment]
TODO: translate the mouse-over for the Tier levels

~~https://github.com/ericnelson0/DIM/blob/builder-i18n/app/scripts/minmax/dimMinMax.controller.js#L73~~

~~doesn't work after `npm run generate-css` so something in the css made this fix no longer reliable.~~

**Comment by ericnelson0** [comment]
We could try to either wrap the overflow or use an ellipsis for really long words.

You're saying the fix for equipping masks/things with no stats is no longer reliable?

**Comment by delphiactual** [comment]
Yeah, this is what happens:
screenshot 2016-11-01 09 36 58
~~And we still need to capture the error for displaying the blank talentGrid~~

**Comment by delphiactual** [comment]
~~I think wrapping is the way to go instead of ellipsis, it will give the german translation the same feel as the others instead of a one off...~~

**Comment by delphiactual** [comment]
I made it to where Loadout Builder will not pull no stat items into the Locked Items, seems like the best idea.
EDIT:
Maybe pop a toaster if we do not equip a no-stat item so users know it is not a bug

**Comment by delphiactual** [comment]
To fix the buttons it is a scope issue, here is the issue raised with angular-translate and the solution the provided. 

https://github.com/angular-translate/angular-translate/issues/1006#issuecomment-93023564

I'm still learning JS so if you could handle that it would be great when I tried the prefix method I couldn't get the mainmodel variable to work in the controller.

**Comment by delphiactual** [comment]
Just the stat name on the popup needs translate. I cannot find where this is being set at in the code.
screenshot 2016-11-01 15 20 47
- [x] Ready for merge!

**Comment by ericnelson0** [comment]
The code for that popup should be from the <code>dimStats.directive.js</code> file.

**Comment by delphiactual** [comment]
Messed up a commit with git, will open new PR

https://github.com/ericnelson0/DIM/pull/3

**Pull request closed without merging**
